# Generated by Django 4.2 on 2023-04-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rights', models.PositiveSmallIntegerField()),
                ('percent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Completion',
                'verbose_name_plural': 'Completions',
            },
        ),
    ]
