# Generated by Django 4.2 on 2023-04-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completion',
            name='total',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
