# Generated by Django 4.2 on 2023-04-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='cat',
            new_name='category',
        ),
    ]
