# Generated by Django 4.2 on 2023-04-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_max_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'position')},
        ),
    ]
