# Generated by Django 4.2 on 2023-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_option_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
