# Generated by Django 4.2 on 2023-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_option_position_alter_question_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
