# Generated by Django 4.2 on 2023-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'position')},
        ),
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'title'), ('question', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'position'), ('quiz', 'title')},
        ),
    ]
