# Generated by Django 4.2 on 2023-04-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_option_unique_together_alter_option_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'title')},
        ),
        migrations.RemoveField(
            model_name='option',
            name='position',
        ),
        migrations.RemoveField(
            model_name='question',
            name='position',
        ),
    ]
